module.exports = {
  ENTRY_POINT: 'client/index.js',
  HTML: 'client/index.html',
  OUT: 'bundle.js',
  MINIFIED_OUT: 'bundle.min.js',
  AUTH_ENTRY_POINT: 'client/auth.js',
  AUTH_HTML: 'client/auth.html',
  AUTH_OUT: 'auth-bundle.js',
  AUTH_MINIFIED_OUT: 'auth-bundle.min.js',
  DEST: 'dist',
  LOGO: 'client/Logo.jsx',
  SRC: [
    'client/**/*.js',
    'client/**/*.jsx',
    '!client/auth.js',
    '!client/auth-app/*',
    '!client/**/*.test.jsx',
  ],
  AUTH_SRC: ['client/auth.js, client/auth-app/**/*.js', 'client/auth-app/**/*.jsx'],
};
